### ISSUE TITLE
Build results in ClassNotFoundException: Didn't find class "androidx.lifecycle.DefaultLifecycleObserver

### ISSUE THREAD

**Issue by SaarYogev** [SUPERCILEX/Robot-Scouter#288]
### Step 1: Describe your environment

Windows 10 64-bit
Android Studio 4.0 Canary 9

### Step 2: Describe the problem:

Whenever I try to build the app, I get the following exception:

`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/DefaultLifecycleObserver$-CC;`
`Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.DefaultLifecycleObserver$-CC"` ...

I'm building in debug mode, and also tried `isUseProguard=false` to make sure that's not the issue.

When building, I also get the following warning:
`The option setting 'android.enableR8=false' is deprecated.null`
along with a few *deprecated* warnings (`isConnected`, `getExternalStoragePublicDirectory`, etc.) which I assume isn't special.

I tried to use `gradle setup`, `gradle presubmit`,and replaced `google-services.json`, as written in `README.md#Environment setup`, that also didn't help.

This bug prevents me from contributing in any way to the repository, as I can't check my code.

Here is the full debug log, in case it's needed:

02/15 12:19:33: Launching 'android-base' on Pixel 3a XL Android Q.
$ adb shell am start -n "com.supercilex.robotscouter.debug/com.supercilex.robotscouter.HomeActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.supercilex.robotscouter.debug | com.supercilex.robotscouter.debug.test
Waiting for application to come online: com.supercilex.robotscouter.debug | com.supercilex.robotscouter.debug.test
Connected to process 9341 on device 'emulator-5554'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application com.supercilex.robotscouter.debug is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
Connecting to com.supercilex.robotscouter.debug
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application com.supercilex.robotscouter.debug is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/System.out: Debugger has connected
    waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8607', transport: 'socket'
I/chatty: uid=10133(com.supercilex.robotscouter.debug) identical 3 lines
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10133(com.supercilex.robotscouter.debug) identical 1 line
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1356)
W/otscouter.debu: JIT profile information will not be recorded: profile file does not exits.
I/MultiDex: VM with version 2.1.0 has multidex support
    Installing application
    VM has multidex support, MultiDex support library is disabled.
D/SplitCompat: FileStorage: initializing (files directory = /data/user/0/com.supercilex.robotscouter.debug/files, versionCode = 1)
I/LoadedApk: No resource references to update in package com.supercilex.robotscouter.debug.trash
I/LoadedApk: No resource references to update in package com.supercilex.robotscouter.debug.templates
I/LoadedApk: No resource references to update in package com.supercilex.robotscouter.debug.teams
I/LoadedApk: No resource references to update in package com.supercilex.robotscouter.debug.settings
I/LoadedApk: No resource references to update in package com.supercilex.robotscouter.debug.scouts
I/LoadedApk: No resource references to update in package com.supercilex.robotscouter.debug.exports
I/LoadedApk: No resource references to update in package com.supercilex.robotscouter.debug.autoscout
W/ComponentDiscovery: Class com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar is not an found.
    java.lang.ClassNotFoundException: com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.google.firebase.components.ComponentDiscovery.instantiate(com.google.firebase:firebase-components@@16.0.0:80)
        at com.google.firebase.components.ComponentDiscovery.discover(com.google.firebase:firebase-components@@16.0.0:73)
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@19.3.0:404)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:300)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar" on path: DexPathList[[zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/base.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_autoscout.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_exports.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_scouts.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_settings.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_teams.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_templates.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_trash.apk"],nativeLibraryDirectories=[/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at com.google.firebase.components.ComponentDiscovery.instantiate(com.google.firebase:firebase-components@@16.0.0:80) 
        at com.google.firebase.components.ComponentDiscovery.discover(com.google.firebase:firebase-components@@16.0.0:73) 
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@19.3.0:404) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:300) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253) 
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066) 
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
V/FA: Registered activity lifecycle callback
W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
W/otscouter.debu: Verification of void com.google.android.gms.measurement.internal.zzey.zzaa() took 117.328ms
W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
I/FirebaseInitProvider: FirebaseApp initialization successful
I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
I/CrashlyticsCore: Initializing Crashlytics Core 2.7.0.33
I/CrashlyticsInitProvider: CrashlyticsInitProvider initialization successful
D/LeakCanary: Installing AppWatcher
I/otscouter.debu: Waiting for a blocking GC ClassLinker
I/otscouter.debu: Waiting for a blocking GC ClassLinker
I/otscouter.debu: Waiting for a blocking GC ClassLinker
W/Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
I/otscouter.debu: WaitForGcToComplete blocked ClassLinker on HeapTrim for 71.317ms
I/otscouter.debu: Waiting for a blocking GC ClassLinker
    WaitForGcToComplete blocked ClassLinker on ClassLinker for 70.617ms
I/otscouter.debu: WaitForGcToComplete blocked ClassLinker on ClassLinker for 65.688ms
W/otscouter.debu: Verification of com.google.android.gms.tasks.Task com.supercilex.robotscouter.core.data.DatabaseKt.firestoreBatch(kotlin.jvm.functions.Function1) took 3.672s
W/otscouter.debu: Verification of void com.supercilex.robotscouter.feature.teams.TeamListFragment.<init>() took 3.684s
W/otscouter.debu: Verification of java.lang.Object com.bumptech.glide.load.engine.bitmap_recycle.LruArrayPool.getArrayForKey(com.bumptech.glide.load.engine.bitmap_recycle.LruArrayPool$Key) took 3.688s
W/otscouter.debu: Verification of com.google.android.gms.internal.measurement.zzcj com.google.android.gms.internal.measurement.zzci.zza(java.io.File) took 3.629s
I/otscouter.debu: Waiting for a blocking GC ClassLinker
I/otscouter.debu: Waiting for a blocking GC ClassLinker
I/otscouter.debu: WaitForGcToComplete blocked ClassLinker on HeapTrim for 214.141ms
I/otscouter.debu: WaitForGcToComplete blocked ClassLinker on ClassLinker for 43.374ms
W/otscouter.debu: Verification of java.lang.String com.supercilex.robotscouter.core.data.model.TeamsKt.getNames(java.util.Collection) took 214.774ms
D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
W/RenderThread: type=1400 audit(0.0:26): avc: denied { write } for name="property_service" dev="tmpfs" ino=6917 scontext=u:r:untrusted_app_27:s0:c133,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0 app=com.supercilex.robotscouter.debug
I/otscouter.debu: Waiting for a blocking GC ClassLinker
W/otscouter.debu: Verification of void com.google.android.gms.internal.measurement.zzlh.<init>() took 133.267ms
W/otscouter.debu: Verification of androidx.core.content.res.FontResourcesParserCompat$FamilyResourceEntry androidx.core.content.res.FontResourcesParserCompat.readFamily(org.xmlpull.v1.XmlPullParser, android.content.res.Resources) took 204.180ms
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
W/otscouter.debu: Verification of androidx.room.RoomOpenHelper$ValidationResult androidx.work.impl.WorkDatabase_Impl$1.onValidateSchema(androidx.sqlite.db.SupportSQLiteDatabase) took 144.231ms
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
W/otscouter.debu: Verification of void com.google.android.gms.internal.measurement.zzmu.<clinit>() took 135.562ms
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
V/FA: onActivityCreated
W/otscouter.debu: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/otscouter.debu: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@c0811cf
W/otscouter.debu: Verification of void com.google.android.gms.internal.measurement.zzlv.<init>() took 230.923ms
I/otscouter.debu: WaitForGcToComplete blocked ClassLinker on ClassLinker for 1.413s
I/Firestore: (21.3.1) [FirestoreClient]: Initializing. user=null
W/DynamiteModule: Local module descriptor class for providerinstaller not found.
I/DynamiteModule: Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller: Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/otscouter.debu: The ClassLoaderContext is a special shared library.
I/otscouter.debu: The ClassLoaderContext is a special shared library.
V/FA: App measurement collection enabled
I/Firestore: (21.3.1) [Persistence]: Starting transaction: Start MutationQueue
V/FA: App measurement enabled for app package, google app id: com.supercilex.robotscouter.debug, 1:408060214365:android:0708d541318cee269be1b4
I/otscouter.debu: The ClassLoaderContext is a special shared library.
I/otscouter.debu: The ClassLoaderContext is a special shared library.
W/otscouter.debu: Accessing hidden field Ldalvik/system/BaseDexClassLoader;->pathList:Ldalvik/system/DexPathList; (greylist, reflection, allowed)
W/otscouter.debu: Accessing hidden field Ldalvik/system/DexPathList;->nativeLibraryDirectories:Ljava/util/List; (greylist, reflection, allowed)
    Accessing hidden field Ldalvik/system/DexPathList;->systemNativeLibraryDirectories:Ljava/util/List; (greylist, reflection, allowed)
    Accessing hidden field Ldalvik/system/DexPathList;->nativeLibraryPathElements:[Ldalvik/system/DexPathList$NativeLibraryElement; (greylist, reflection, allowed)
    Accessing hidden method Ldalvik/system/DexPathList;->makePathElements(Ljava/util/List;)[Ldalvik/system/DexPathList$NativeLibraryElement; (greylist, reflection, allowed)
V/NativeCrypto: Registering com/google/android/gms/org/conscrypt/NativeCrypto's 284 native methods...
W/otscouter.debu: Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
I/FA: App measurement initialized, version: 21028
    To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.supercilex.robotscouter.debug
D/FA: Debug-level message logging enabled
I/otscouter.debu: Waiting for a blocking GC ClassLinker
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/ProviderInstaller: Installed default security provider GmsCore_OpenSSL
I/otscouter.debu: WaitForGcToComplete blocked ClassLinker on ClassLinker for 240.111ms
W/otscouter.debu: Verification of void com.supercilex.robotscouter.feature.teams.TutorialObserverBase.onDestroy(androidx.lifecycle.LifecycleOwner) took 242.490ms
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.supercilex.robotscouter.debug, PID: 9341
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/DefaultLifecycleObserver$-CC;
        at com.supercilex.robotscouter.feature.teams.TutorialObserverBase.onCreate(Unknown Source:0)
        at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:51)
        at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:583)
        at androidx.fragment.app.FragmentStateManager.restoreViewState(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2621)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2569)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at com.supercilex.robotscouter.HomeActivity.onStart(HomeActivity.kt:223)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.DefaultLifecycleObserver$-CC" on path: DexPathList[[zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/base.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_autoscout.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_exports.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_scouts.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_settings.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_teams.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_templates.apk", zip file "/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/split_trash.apk"],nativeLibraryDirectories=[/data/app/com.supercilex.robotscouter.debug-GSjRQNBQJaoFwWJOudGWzw==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 39 more
V/FA: Connecting to remote service
V/FA: Connection attempt already in progress
D/FA: Setting app measurement enabled (FE): true
D/FA: Updating Scion state (FE)
V/FA: Connection attempt already in progress
I/FA: Tag Manager is not found and thus will not be used
V/FA: Connection attempt already in progress
E/CrashlyticsCore: Failed to execute task.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
        at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:321)
        at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:301)
        at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:42)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:2187)
I/Process: Sending signal. PID: 9341 SIG: 9
Disconnected from the target VM, address: 'localhost:8607', transport: 'socket'

**Comment by SUPERCILEX** [comment]
Oh yeah, Android Studio is dumb. At some point, I'll get around to reporting that bug. You have to use `./gradlew installDebug`.

**Comment by SaarYogev** [comment]
I bumped the `minSdkVersion` to get rid of `MultiDex` problem, and the problem persists. My main suspect is `FirebaseConfigKtxRegistrar`, which raises error in several occasions:

-  `W/ComponentDiscovery: Class com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar is not an found.`
- `java.lang.ClassNotFoundException: com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar`
- `Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar"`

**Comment by SaarYogev** [comment]
Oh thanks, can't believe that's such an easy workaround 😅.
Maybe it should be added to README.md#Environment setup then?
If you don't have the time I can try and make the PR.

**Comment by SUPERCILEX** [comment]
Well it's not a Robot Scouter bug though, Studio's broken. Lemme just file an issue.

**Comment by SUPERCILEX** [comment]
Done: https://issuetracker.google.com/issues/149567835
